name: "Android CI"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Fetching Materials"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      -
        name: Construction
        run: |
            git clone -b main --single-branch https://github.com/ProjectRobust/RobustBatteryService Build
            cd Build
            ./gradlew build
